---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("cansim")
install.packages("cancensus")
```


```{r}
library(networkD3)
getwd()
library(cansim)
library(cancensus)
```


```{r}
nodes <- read.csv(file="nodes.csv", as.is=TRUE)
nodes <- data.frame(nodes)
colnames(nodes)<- c("name",    "ID",    "node_group")
rownames(nodes) <- seq(1,length(nodes[,1]))
links <- read.csv(file="links.csv")
links <- data.frame(links)
colnames(links)<- c("source", "target", "value", "group_type")
rownames(links) <- seq(1,length(links[,1]))
#master_plan <-
 sankeyNetwork(Links = links, Nodes = nodes, Source = "source",
            Target = "target", Value = "value", NodeID = "name",
             fontSize = 14, nodeWidth = 10, LinkGroup = "group_type",  NodeGroup = NULL,
           colourScale = JS("d3.scaleOrdinal(d3.schemeCategory20);"), sinksRight = FALSE, iterations =18, height = 800, width=1200, nodePadding = 10)
```

Get data

For CANSIM tables: looking for ones with GEOUID

```{r}
options(cansim.cache_path="data/census_cache")
list_cansim_tables()

list_census_datasets(use_cache = FALSE, quiet = FALSE)
list_census_regions("CA16", use_cache = FALSE, quiet = TRUE)
list_census_vectors("CA16", use_cache = TRUE, quiet = TRUE)
lister <- list_census_vectors("CA16", use_cache = TRUE, quiet = TRUE)
lister[4001:6623,]
```

